Vagrant.configure("2") do |config|

  config.vm.box = "sbeliakou/centos"

config.vm.define :zserver do |zserver|
      zserver.vm.host_name = "zabbix.server"
      zserver.vm.network "private_network", ip:"192.168.56.101"
      zserver.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
      end
      zserver.vm.provision "shell", path: "Server.sh"
  end
config.vm.define :zagent do |zagent|
      zagent.vm.host_name = "zabbix.agent"
      zagent.vm.network "private_network", ip:"192.168.56.102"
      zagent.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
      end
     zagent.vm.provision "shell", path: "Server.sh"
  end
end
