Vagrant.configure("2") do |config|

  config.vm.box = "sbeliakou/centos"

config.vm.define :elk do |elk|
      elk.vm.host_name = "ELK"
      elk.vm.network "private_network", ip:"192.168.56.101"
      elk.vm.provider :virtualbox do |vb|
      vb.memory = "3072"
      end
      elk.vm.provision "shell", path: "tomcat.sh"
  end
config.vm.define :tomcat do |tomcat|
      tomcat.vm.host_name = "TOMCAT"
      tomcat.vm.network "private_network", ip:"192.168.56.102"
      tomcat.vm.provider :virtualbox do |vb|
      vb.memory = "3072"
      end
     tomcat.vm.provision "shell", path: "ELK.sh"
  end
end
